# Generated by Django 5.2.6 on 2025-09-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_amlrequest_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amlrequest',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
