# Generated by Django 5.2.6 on 2025-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amlrequest',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
